test 1.17

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -1,35 +1,35 @@
 name: integration
 on: [ push, workflow_dispatch ]
 jobs:
-  install_go_tip:
-    name: install tip
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - ubuntu-20.04
-          - windows-2019
-    runs-on: ${{ matrix.os }}
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - uses: actions/checkout@v2
-      - id: setup_go
-        name: install tip
-        uses: ./
-        with:
-          go-version: tip
-      - name: outputs
-        run: |
-          echo '*********** env ************'
-          env
-          echo '*********** go env ***********'
-          go env
-          echo '${{ toJson( steps.setup_go.outputs ) }}' | jq .
-          go version
-          set -ex
-          [[ "$(go version)" == *"devel"* ]]
+#  install_go_tip:
+#    name: install tip
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os:
+#          - ubuntu-20.04
+#          - windows-2019
+#    runs-on: ${{ matrix.os }}
+#    defaults:
+#      run:
+#        shell: bash
+#    steps:
+#      - uses: actions/checkout@v2
+#      - id: setup_go
+#        name: install tip
+#        uses: ./
+#        with:
+#          go-version: tip
+#      - name: outputs
+#        run: |
+#          echo '*********** env ************'
+#          env
+#          echo '*********** go env ***********'
+#          go env
+#          echo '${{ toJson( steps.setup_go.outputs ) }}' | jq .
+#          go version
+#          set -ex
+#          [[ "$(go version)" == *"devel"* ]]
   install_go:
     name: install go
     strategy:
@@ -37,20 +37,20 @@ jobs:
       matrix:
         os:
           - ubuntu-20.04
-          - ubuntu-18.04
-          - windows-2019
-          - macos-10.15
+#          - ubuntu-18.04
+#          - windows-2019
+#          - macos-10.15
     runs-on: ${{ matrix.os }}
     defaults:
       run:
         shell: bash
     steps:
       - uses: actions/checkout@v2
-      - id: setup_go_1_15_5
-        name: install 1.15.5
+      - id: setup_go_1_17
+        name: install 1.17
         uses: ./
         with:
-          go-version: '1.15.5'
+          go-version: '1.17'
       - name: outputs
         run: |
           echo '*********** env ************'
@@ -65,74 +65,74 @@ jobs:
           [[ '${{steps.setup_go_1_15_5.outputs.GOTOOLDIR}}' == *"1.15.5"* ]]
 
 
-      - id: setup_go_1_16rc1
-        name: install 1.16rc1
-        uses: ./
-        with:
-          go-version: '1.16rc1'
-      - name: outputs
-        run: |
-          echo '*********** env ************'
-          env
-          echo '*********** go env ***********'
-          go env
-          echo '${{ toJson( steps.setup_go_1_16rc1.outputs ) }}' | jq .
-          go version
-          set -ex
-          [[ "$(go version)" == *"1.16rc1"* ]]
-          [[ '${{steps.setup_go_1_16rc1.outputs.GOROOT}}' == *"16rc1"* ]]
-          [[ '${{steps.setup_go_1_16rc1.outputs.GOTOOLDIR}}' == *"16rc1"* ]]
-
-
-      - id: setup_go_all
-        name: install '*'
-        uses: ./
-        with:
-          go-version: '*'
-      - name: outputs
-        run: |
-          echo '*********** env ************'
-          env
-          echo '*********** go env ***********'
-          go env
-          echo '${{ toJson( steps.setup_go_all.outputs ) }}' | jq .
-          go version
-
-
-      - id: setup_go_1_15_5_again
-        name: install 1.15.5 again
-        uses: ./
-        with:
-          go-version: '1.15.x <1.15.6'
-      - name: outputs
-        run: |
-          echo '*********** env ************'
-          env
-          echo '*********** go env ***********'
-          go env
-          echo '${{ toJson( steps.setup_go_1_15_5_again.outputs ) }}' | jq .
-          go version
-          set -ex
-          [[ "$(go version)" == *"1.15.5"* ]]
-          [[ '${{steps.setup_go_1_15_5_again.outputs.GOROOT}}' == *"1.15.5"* ]]
-          [[ '${{steps.setup_go_1_15_5_again.outputs.GOTOOLDIR}}' == *"1.15.5"* ]]
-
-
-      - id: setup_go_1_13_x
-        name: install 1.13.x
-        uses: ./
-        with:
-          go-version: '1.13.x'
-          ignore-local: true
-      - name: outputs
-        run: |
-          echo '*********** env ************'
-          env
-          echo '*********** go env ***********'
-          go env
-          echo '${{ toJson( steps.setup_go_1_13_x.outputs ) }}' | jq .
-          go version
-          set -ex
-          [[ "$(go version)" == *"1.13"* ]]
-          [[ '${{steps.setup_go_1_13_x.outputs.GOROOT}}' == *"1.13"* ]]
-          [[ '${{steps.setup_go_1_13_x.outputs.GOTOOLDIR}}' == *"1.13"* ]]
+#      - id: setup_go_1_16rc1
+#        name: install 1.16rc1
+#        uses: ./
+#        with:
+#          go-version: '1.16rc1'
+#      - name: outputs
+#        run: |
+#          echo '*********** env ************'
+#          env
+#          echo '*********** go env ***********'
+#          go env
+#          echo '${{ toJson( steps.setup_go_1_16rc1.outputs ) }}' | jq .
+#          go version
+#          set -ex
+#          [[ "$(go version)" == *"1.16rc1"* ]]
+#          [[ '${{steps.setup_go_1_16rc1.outputs.GOROOT}}' == *"16rc1"* ]]
+#          [[ '${{steps.setup_go_1_16rc1.outputs.GOTOOLDIR}}' == *"16rc1"* ]]
+#
+#
+#      - id: setup_go_all
+#        name: install '*'
+#        uses: ./
+#        with:
+#          go-version: '*'
+#      - name: outputs
+#        run: |
+#          echo '*********** env ************'
+#          env
+#          echo '*********** go env ***********'
+#          go env
+#          echo '${{ toJson( steps.setup_go_all.outputs ) }}' | jq .
+#          go version
+#
+#
+#      - id: setup_go_1_15_5_again
+#        name: install 1.15.5 again
+#        uses: ./
+#        with:
+#          go-version: '1.15.x <1.15.6'
+#      - name: outputs
+#        run: |
+#          echo '*********** env ************'
+#          env
+#          echo '*********** go env ***********'
+#          go env
+#          echo '${{ toJson( steps.setup_go_1_15_5_again.outputs ) }}' | jq .
+#          go version
+#          set -ex
+#          [[ "$(go version)" == *"1.15.5"* ]]
+#          [[ '${{steps.setup_go_1_15_5_again.outputs.GOROOT}}' == *"1.15.5"* ]]
+#          [[ '${{steps.setup_go_1_15_5_again.outputs.GOTOOLDIR}}' == *"1.15.5"* ]]
+#
+#
+#      - id: setup_go_1_13_x
+#        name: install 1.13.x
+#        uses: ./
+#        with:
+#          go-version: '1.13.x'
+#          ignore-local: true
+#      - name: outputs
+#        run: |
+#          echo '*********** env ************'
+#          env
+#          echo '*********** go env ***********'
+#          go env
+#          echo '${{ toJson( steps.setup_go_1_13_x.outputs ) }}' | jq .
+#          go version
+#          set -ex
+#          [[ "$(go version)" == *"1.13"* ]]
+#          [[ '${{steps.setup_go_1_13_x.outputs.GOROOT}}' == *"1.13"* ]]
+#          [[ '${{steps.setup_go_1_13_x.outputs.GOTOOLDIR}}' == *"1.13"* ]]
